# Partial config (public stuff)

libraries:                                      # Library mappings must have a colon (:) placed after them
  Movies:
    library_name: Movies
    metadata_path:
      - repo: collections/actors/movies
      - repo: collections/awards/movies
      - repo: collections/best/movies
      - repo: collections/countries/movies
      - repo: collections/decades/movies
      - repo: collections/genres/movies
      - repo: collections/holidays/movies
      - repo: collections/lists/movies
      - repo: collections/memoriam/movies
      - repo: collections/networks/movies
      - repo: collections/new/movies
      - repo: collections/random/movies
      - repo: collections/recommendations/movies
      - repo: collections/trending/movies
      - repo: collections/years/movies
  4K Movies:
    library_name: Movies (4K)
    metadata_path:
      - repo: collections/actors/movies
      - repo: collections/awards/movies
      - repo: collections/best/movies
      - repo: collections/countries/movies
      - repo: collections/decades/movies
      - repo: collections/genres/movies
      - repo: collections/holidays/movies
      - repo: collections/lists/movies
      - repo: collections/memoriam/movies
      - repo: collections/networks/movies
      - repo: collections/new/movies
      - repo: collections/random/movies
      - repo: collections/recommendations/movies
      - repo: collections/trending/movies
      - repo: collections/years/movies
  TV Shows:
    library_name: TV Shows
    metadata_path:
      - repo: collections/actors/shows
      - repo: collections/awards/shows
      - repo: collections/best/shows
      - repo: collections/countries/shows
      - repo: collections/decades/shows
      - repo: collections/genres/shows
      - repo: collections/holidays/shows
      - repo: collections/lists/shows
      - repo: collections/memoriam/shows
      - repo: collections/networks/shows
      - repo: collections/new/shows
      - repo: collections/random/shows
      - repo: collections/recommendations/shows
      - repo: collections/trending/shows
      - repo: collections/years/shows
  4K TV Shows:
    library_name: TV Shows (4K)
    metadata_path:
      - repo: collections/actors/shows
      - repo: collections/awards/shows
      - repo: collections/best/shows
      - repo: collections/countries/shows
      - repo: collections/decades/shows
      - repo: collections/genres/shows
      - repo: collections/holidays/shows
      - repo: collections/lists/shows
      - repo: collections/memoriam/shows
      - repo: collections/networks/shows
      - repo: collections/new/shows
      - repo: collections/random/shows
      - repo: collections/recommendations/shows
      - repo: collections/trending/shows
      - repo: collections/years/shows
